In [1]:
import numpy as np

In [2]:
myArray = np.arange(0,15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [6]:
myArray[2:5]

array([2, 3, 4])

In [7]:
myArray[3:8] = -5

In [8]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
myArray2 = np.arange(0,24)

In [10]:
myArray2Cut = myArray2[2:5]

In [11]:
myArray2Cut

array([2, 3, 4])

In [12]:
myArray2Cut[:] = 100

In [13]:
myArray2Cut

array([100, 100, 100])

In [14]:
myArray2

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [15]:
exArray = np.arange(0,24)

In [16]:
ex2Array = exArray.copy()

In [17]:
ex2Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ex2Array[:]= 100

In [19]:
ex2Array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
exArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])