In [3]:
import numpy as np

In [2]:
myArray = np.arange(0,15)

In [3]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myArray[5]

5

In [6]:
myArray[2:5]

array([2, 3, 4])

In [7]:
myArray[3:8] = -5

In [8]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
myArray2 = np.arange(0,24)

In [10]:
myArray2Cut = myArray2[2:5]

In [11]:
myArray2Cut

array([2, 3, 4])

In [12]:
myArray2Cut[:] = 100

In [13]:
myArray2Cut

array([100, 100, 100])

In [14]:
myArray2

array([  0,   1, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [15]:
exArray = np.arange(0,24)

In [16]:
ex2Array = exArray.copy()

In [17]:
ex2Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
ex2Array[:]= 100

In [19]:
ex2Array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
exArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [5]:
myList = [[1,2,3],[2,3,4],[3,4,5]]

In [6]:
myMatrixList = np.array(myList)

In [7]:
myMatrixList

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
myMatrixList[0]

array([1, 2, 3])

In [9]:
myMatrixList[0][1]

2

In [10]:
myMatrixList[0,1]

2

In [11]:
myMatrixList[1:,2]

array([4, 5])

In [12]:
myMatrixList[0:,2]

array([3, 4, 5])

In [15]:
myMatrixList[2:,2:]

array([[5]])

In [16]:
myMatrixList[[0,1]]

array([[1, 2, 3],
       [2, 3, 4]])

## Operations

In [19]:
list = np.random.randint(1,100,10)

In [20]:
list

array([76, 63, 28, 54, 25, 13, 52, 25, 32, 26])

In [21]:
list > 24

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True])

In [22]:
list1 = list > 50

In [24]:
list1

array([ True,  True, False,  True, False, False,  True, False, False,
       False])

In [26]:
list[list1]

array([76, 63, 54, 52])

In [27]:
list[list>30]

array([76, 63, 54, 52, 32])

In [29]:
list + list1

array([77, 64, 28, 55, 25, 13, 53, 25, 32, 26])

In [30]:
list / list1

C:\Users\user\AppData\Local\Temp\ipykernel_17652\1364610129.py:1: RuntimeWarning: divide by zero encountered in divide
  list / list1


array([76., 63., inf, 54., inf, inf, 52., inf, inf, inf])

In [31]:
np.sqrt(list)

array([8.71779789, 7.93725393, 5.29150262, 7.34846923, 5.        ,
       3.60555128, 7.21110255, 5.        , 5.65685425, 5.09901951])

In [32]:
np.max(list)

76